LostArtefacts/Tomb1Main

src/global/vars.h, src/specific/frontend.c, src/specific/hwr.c, src/specific/shell.c
The call to `HWR_DownloadTextures` seems to be some artifact from another platform – ATI3DCIF handles changing render settings on the fly just fine, as evidenced by the F3 button working in the OG TombATI.exe. Removing it makes the problem go away with seemingly no side effects. Since we now know the reason why the chunks that were removed in recent decompilation efforts existed, and those routines no longer seem to be necessary, I also removed the NOTE comments.
Also the reported issue demonstrates that it doesn't make sense to keep those prim strip renders out of the `if` blocks, since they're all black anyway, so I pulled them back into the `if` blocks like they were arranged in the original .exe.
=> specific: fix unloading textures (closes #158)

src/specific/input.c
probably doesn't happen for you because Linux lives in the A world, while my Windows is W so they mismatch for me.
=> ENUM type mismatch

src/specific/init.c
explicitly clear the memory to 0.
GCC does this by default, other compilers don't. MSVC sets it to 0xcdcdcdcd for debugging purposes.
sadly the trigger data in Folly has an invalid item number which is usually fine because it gets an all null, the floor is null and so nothing is called. If this is OG bug, or now manifesting from some other changes I don't know.
=> clear GameMemory

src/game/draw.c
`CalculateObjectLighting` in itself calls `S_CalculateLight` so the call underneath felt extraneous. I couldn't get `CalculateObjectLighting` to calculate the light correctly, though, so I just decided to throw mesh and matrix information away and go with just the intensity of the light at the pickup location. Pickups are supposed to be small anyway so it shouldn't matter.
=> game/draw: simplify 3d pickup lighting

src/game/demo.c, src/game/game.c, src/game/inventry.c, src/game/invfunc.c, src/game/option.c, src/game/overlay.c, src/game/pause.c, src/game/requester.c, src/game/setup.c, src/game/text.c, src/game/text.h, src/global/const.h, src/global/types.h, src/global/vars.c, src/global/vars.h, src/specific/init.c, src/specific/shell.c
Similar refactors to what we have in #186 . One curiosity is the introduction of `on_remove` hook in `TEXSTRING*` to achieve inversion of control with regards to global pointer invalidation for static textstrings (details in the commit message).
=> Text refactor

src/game/objects/pickup.c
In TR1 and TR2, possibly in the later games too, Lara has a larger pickup radius if she's facing away from the item. This is counter-intuitive. This commit adjusts it so that the radius is the same regardless of her orientation in reference to the collectibles.
Closes #195
=> objects/pickup: make pickup radius broader

bin/cfg/Tomb1Main_gameflow.json5
Closes #259
We have a mechanism in place that guesses the FMV file extension. This pull request ensures that if the user has both .rpl and high res .avi movies, the game will choose .avi first. If .avi does not exist, the game will try FMVs sequentially according to the predefined list of hardcoded file extensions, until it reaches .rpl which it will play as usual.
=> bin: change .rpl to .avi

Makefile, bin/cfg/Tomb1Main.json5, src/config.c, src/config.h, src/game/option_graphics.c, src/game/overlay.c, src/game/settings.c, src/gfx/3d/3d_renderer.c, src/specific/s_input.c, src/specific/s_output.c
The motivation for this PR has two sources:
- TombATI makes it possible to change the anisotropy filter value
- I am facing a problem on wine that makes the game unplayable if there are many textures and the anisotropy filter is enabled
=> Make anisotropy filter value configurable

src/specific/s_output.c
Closes #288.
I couldn't reproduce the original issue so this is a blind fix.
=> s/output: clear picture surface before blit

src/global/const.h
Tiny resolutions were removed, but `RESOLUTIONS_SIZE` was still set to 12. So, garbage values were showing as resolution options from the sunglasses menu.
=> gfx: fix garbage value resolutions showing as options

src/game/game.c
Resolves #273.
I was thinking maybe the game should highlight the slot you most recently saved OR loaded instead of the most recent overall one. Idk just something I was thinking of when I was looking at the code.
=> game: fix top offscreen load game selection

src/gfx/3d/3d_renderer.c, src/specific/s_output.c
When the shader compilation fails, the game exits and crashes on an attempt to free textures. The problem is that the renderer initialization failed, and texture array initialization comes after that, so the shutdown routine sees garbage data.
=> gfx: fix crash when shader compilation fails

src/game/cinema.c, src/game/cinema.h, src/game/control.c, src/game/control.h, src/game/control_pause.c, src/game/demo.c, src/game/draw.c, src/game/draw.h, src/game/game.c, src/game/game.h, src/game/gameflow.c, src/game/inventry.c, src/game/output.c, src/game/output.h, src/gfx/2d/2d_surface.c, src/gfx/screenshot.c, src/gfx/screenshot.h, src/specific/s_misc.c, src/specific/s_misc.h, src/specific/s_output.c
First, some context. The main game loop looks like this:
1. Move things around, run game logic (ControlPhase)
2. Draw things (DrawPhase) to the back buffer
3. Move the back buffer to the front buffer (technically we call it flipping buffers, but support for reading from the backbuffer after a flip is fragmentary, so we cannot rely on the "flip" property).
Sometimes step 1 causes additional drawing. One of such examples is the inventory and the pause screen – if the player decides to open them during ControlPhase, the game runs internal loops within ControlPhase.
To display the main menu, currently the game calls `glReadPixels()` from the GL_FRONT buffer. This is bad, because support for reading from the front buffer is fragmentary and varies between GPU vendors. **This pull request …
=> gfx: implement menu backgrounds properly

src/specific/s_shell.c
Resolves #280.
The SDL high DPI flag doesn't work yet. It's still a WIP. The progress can be tracked [here](https://github.com/libsdl-org/SDL/issues/4908).
This solution fixes the game resolution for me. I have a 1440p display with 125% scaling. Before, the game would auto detect 2048x1152 as my resolution. Now, it correctly starts at 1440p.
=> Support DPI scaling on Windows

src/game/cinema.c, src/game/control.c, src/game/game.c, src/game/shell.c, src/specific/s_fmv.c
Resolves #359.
Scenarios needed to be tested:
(Escape key)
This should trigger inventory on the frame before, and skip the level stats screen on the frame after. Hard to test and can be assumed to work correctly.
This should trigger inventory on the frame before, and skip the FMV on the frame after. Hard to test and can be assumed to work correctly.
Should skip the FMV immediately and then should not trigger the inventory ring.
Should skip the FMV immediately and then not skip the level stats screen until another key is pressed. (scenario not in vanilla TR1)
Should skip the level stats screen immediately and then not skip the FMV until another key is pressed.
Should skip the FMV immediately and then should not trigger the inventory ring.
Should skip the cutscene immediately and then …
=> input: fix certain inputs skipping too many things

src/game/cinema.c, src/game/control_pause.c, src/game/draw.c, src/game/draw.h, src/game/game.c, src/game/gameflow.c, src/game/inventry.c, src/game/output.c, src/game/output.h, src/game/overlay.c, src/gfx/3d/3d_renderer.c, src/gfx/3d/3d_renderer.h, src/global/types.h, src/specific/s_output.c, src/specific/s_output.h
This is continuation of #357 and lays the groundwork for the fade-in / fade-out effects. Rather than rendering the hacky picture buffer, we actually render the game, then a translucent quad, then the inventory.
This causes me to drop FPS.
Normally my game runs at around 12 FPS, but the inventory due to its simplicity renders at 25 FPS. With the new approach, the inventory runs at 8 FPS because it has to render both the game and the inventory ring on every frame.
Nonetheless, in my opinion it is acceptable, because I am running the game on a 4k window with a stupid emulator, which is equivalent of having a super potato machine.
=> Improve overlays

README.md, bin/cfg/Tomb1Main.json5, src/config.c, src/config.h, src/game/control_pause.c, src/game/demo.c, src/game/draw.c, src/game/draw.h, src/game/game.c, src/game/gameflow.c, src/game/inventry.c, src/game/output.c, src/game/output.h, src/game/shell.c, src/gfx/3d/3d_renderer.c, src/gfx/3d/3d_renderer.h, src/specific/s_output.c, src/specific/s_output.h
The fade effects use fixed transparency deltas and thus are FPS dependent. LMK if it's acceptable.
Testing scenarios
=> output: add fade animations

src/game/inventry.c
No changelog entry since it's a mistake introduced by my implementation that was not released yet.
=> inv: fix fade ending one frame too early

CHANGELOG.md, src/game/game.c
Resolves #399.
I tested things like minimizing for multiple demos, credits, pause screens, etc and didn't notice any bugs with this solution.
=> game: fix title menu resuming music after demo when minimized

CHANGELOG.md, README.md, src/game/ai/pod.c
Fixes #250.
This makes empty pods no longer spawn Lara's hips. This is consistent with Stella's walkthrough, that clearly states that these shells are supposed to be "duds". This doesn't break savegames.
=> ai/pod: spawn only objects that are loaded

src/game/control.c, src/game/laramisc.c, src/game/level.c, src/game/savegame.c, src/game/savegame_bson.c, src/game/setup.c, src/global/types.h
This is an internal refactor without value to the end user.
Resolves #212
=> Move Lara's initial hitpoints to STARTINFO

CHANGELOG.md, src/game/sound.c
Resolves #421. Tested heavily on ×5 speed. The scenario I described in #421 was indeed the problem – we just missed one call to the slot deduplication.
=> sound: fix rare audio glitch

CHANGELOG.md, README.md, src/game/ai/pod.c
=> pod: fix pods unhatching on reload if user saves during explosion

CHANGELOG.md, src/game/option_passport.c
...
Ok round 2 sorry. Witholding a README update until arrows are added to all the game option screens which will come in separate PRs. This also includes some option_passport rework. As we discussed, I wanted to get some input on the changes so far.
=> option_passport: add contextual arrows and clean up

CHANGELOG.md, src/game/option_control.c
Resolves #461.
Adds contextual arrows to the control options screen.
...
Just this one and then the graphics menu... Almost done sorry. Video:
https://streamable.com/kgnjdz
=> option_control: add contextual arrows

src/game/option_graphics.c
Offset title bar to match other menus.
...
Pic:
=> option_graphics: offset title bar to match other menus

CHANGELOG.md, README.md, src/game/option_sound.c
Resolves #467.
Fixed sound effects playing rapidly in sound menu if input held down.
...
=> option_sound: fix rapid sound effect if input held down

CHANGELOG.md, src/game/stats.c
Resolves #490.
Fixed music rolling over to the main menu if main menu music is disabled.
...
=> stats: stop all music after final statistics are displayed

src/game/camera.c, src/game/camera.h, src/game/control.c, src/game/game.c, src/game/laramisc.c
Old name                          | New Name                           | Other changes
---                               | ---                                | ---
`InitialiseCamera`                | `Camera_Initialise`                |
`ChaseCamera`                     | `Camera_Chase`                     |
`CombatCamera`                    | `Camera_Combat`                    |
`LookCamera`                      | `Camera_Look`                      |
`FixedCamera`                     | `Camera_Fixed`                     |
`CalculateCamera`                    | `Camera_Update`                    |
`CameraOffsetAdditionalAngle`     | `Camera_OffsetAdditionalAngle`     |
`CameraOffsetAdditionalElevation` | `Camera_OffsetAdditionalElevation` |
`CameraOffsetReset`               | …
=> camera: adhere to naming convention

CHANGELOG.md, src/game/control.c, src/game/demo.c, src/game/game.c, src/game/gameflow.c, src/game/inventry.c, src/game/lara.h, src/game/larafire.c, src/game/laramisc.c, src/game/objects/pickup.c, src/game/objects/scion.c, src/game/option_compass.c, src/game/overlay.c, src/game/savegame.c, src/game/savegame.h, src/game/savegame_bson.c, src/game/savegame_common.h, src/game/savegame_legacy.c, src/game/setup.c, src/game/shell.c, src/game/stats.c, src/global/types.h
...
I'm aware this is not done and does not solve legacy saving/loading. I just wanted to ask you to look over this to confirm this is the correct direction for the data types.
`GAME_STATS` is now in `RESUME_INFO`. `GAME_INFO` now has `RESUME_INFO *start` and `RESUME_INFO *end`.
=> Refactor savegames to use start and current info

CHANGELOG.md, src/game/savegame.c
Resolves #514.
Changed the savegame requestor to remember the user's requested slot number. The requestor no longer highlights the newest savegame slot every time the load game menu is open.
Video: https://streamable.com/wmh6l3
...
=> savegame: changed savegame requestor to remember requested

CHANGELOG.md, src/game/savegame_legacy.c
=> savegame: fix pushables loading for legacy savegames

CHANGELOG.md, README.md, src/config.c, src/config.h, src/game/game/game.c, src/game/music.c, src/game/music.h, src/game/savegame.h, src/game/savegame/savegame_bson.c, src/json/json_base.c, src/json/json_base.h, src/specific/s_audio.h, src/specific/s_audio_stream.c, tools/config/Tomb1Main_ConfigTool/Resources/Lang/en.json, tools/config/Tomb1Main_ConfigTool/Resources/Lang/es.json, tools/config/Tomb1Main_ConfigTool/Resources/Lang/fr.json, tools/config/Tomb1Main_ConfigTool/Resources/specification.json
Added the current music track and timestamp to the savegame so they now persist on load.
=> savegame: save and load current music track and timestamp
