src/game/lara.c
src/specific/input.c

input, lara: improve tr3 sidesteps

---

src/specific/s_hwr.c

This is a safety mechanism so that when the texture loader fails for any reason, the player can see cel-shaded polys instead of an unfriendly error message.
The reason why drawing untextured triangles used to be not working in the past was because we should have been calling `HWR_DisableTextureMode()`.

s/hwr: let people play even with texture errors

---

src/game/inventry.c

demo: fix crash if user inputs during demo ring close

---

src/game/game.c
src/game/game.h
src/game/option_passport.c
src/game/shell.c

Fix offscreen save selection

---

src/game/savegame.c

savegame: fix loading legacy Evil Lara

---

README.md
src/game/lara.c

lara: fix hang bug for stacked rooms

---

src/game/output.c
src/global/types.h

Closes #283.
Copied TR2Main's approach to VBUFs.

output: improve VBuf fidelity

---

src/game/gameflow.c

fix save crystal mode saving before gym level

---

src/game/overlay.c

overlay: fix airbar showing on deaths outside of water

---

src/game/input.c

input: allow holding down forward/back to move through saves

---

src/game/control_pause.c

control_pause: fix ambient noises not pausing on pause screen

---

bin/shaders/2d.fsh
bin/shaders/2d.vsh
bin/shaders/3d.fsh
bin/shaders/3d.vsh

Resolves #327. I'm not sure about the compatibility range. It's working fine on Wine both with and without the bilinear filter.

bin: downgrade shaders to GLSL version 1.30

---

README.md
src/specific/s_fmv.c

s/fmv: let players skip FMVs with the action key

---

README.md
src/specific/s_shell.c

s_shell: mute all sound when game is minimized

---

scripts/generate_init
src/game/gameflow.c
src/game/gameflow.h
src/game/shell.c
src/init.c
src/init.h

gameflow: fix fallback game strings not working

---

src/game/control.c
src/game/traps/lava.c
src/game/traps/lava.h

lava: fix lava trap not setting Lara on fire

---

CHANGELOG.md
README.md
src/config.h
src/game/option_graphics.c
src/specific/s_input.c

option_graphics: fix options flashing with any option change
option_graphic: use bools for graphic settings
Resolves #380.

Fix detail levels text flashing

---

CHANGELOG.md
src/game/fmv.c
src/game/inventry.c
src/game/output.c
src/game/output.h

Improve title menu fades

---

CHANGELOG.md
src/specific/s_fmv.c

s/fmv: do not free up game memory

---

src/game/inventry.c

This is another regression on the unreleased branch.
8eaba246 introduced better waiting for the fade finish for the inventory, however, this revealed a problem with the waiting for the finished fade in case it carries over to the normal gameplay. Because in that fallback branch we didn't restore the camera, it would trigger black frames.

inv: fix black frame after saving

---

CHANGELOG.md
README.md
src/game/game.c
src/game/savegame.c
src/game/savegame.h
src/game/savegame_bson.c

game: fix gun pickups disappearing on save load

---

CHANGELOG.md
README.md
src/filesystem.c
src/filesystem.h
src/game/fmv.c
src/game/fmv.h
src/game/picture.c
src/game/savegame.c
src/game/savegame.h
src/game/savegame_bson.c
src/game/savegame_bson.h
src/game/savegame_common.h
src/game/savegame_legacy.c
src/game/savegame_legacy.h
src/game/shell.c
src/game/shell.h
src/log.c
src/specific/s_audio_stream.c
src/specific/s_fmv.c
src/specific/s_picture.c

Resolves #87. I also simplified path management while at it, as it was quite annoying.
Files in the saves/ directory take precedence over the files scattered in the root directory.
Saving new files always places them in the saves/ directory.

Move saves to a dedicated directory

---

CHANGELOG.md
bin/cfg/Tomb1Main_gameflow.json5
src/specific/s_output.c

s/output: fix drawing floor in cutscene 4

---

CHANGELOG.md
README.md
bin/cfg/Tomb1Main.json5
src/config.c
src/config.h
src/game/laramisc.c
src/game/overlay.c
src/game/savegame.c
src/game/savegame_bson.c
src/game/setup.c

lara: make starting health configurable

---

CHANGELOG.md
src/game/option_compass.c
src/game/stats.c

option/compass: change text order

---

CHANGELOG.md
src/game/game.c
src/game/savegame.c
src/game/savegame_bson.c
src/game/savegame_common.h
src/game/savegame_legacy.c
src/game/setup.c

Fix loading legacy saves

---

CHANGELOG.md
src/game/savegame.c

save: fix saving not updating sg format

---

CHANGELOG.md
src/game/objects/switch.c
src/game/objects/switch.h

switch: add option to walk to switches when nearby

---

src/game/text.c
src/game/text.h

text: add left/right arrow support and new text functions

---

scripts/analyze_memleaks.patch
src/filesystem.c
src/game/gameflow.c
src/game/savegame.c
src/game/savegame_bson.c
src/game/savegame_legacy.c
src/game/text.c
src/gfx/context.c
src/json/json_base.c
src/memory.c
src/memory.h
src/specific/s_output.c

Various cleanups

---

CHANGELOG.md
src/game/option_sound.c
src/global/types.h

option_sound: add contextual arrows

---

CHANGELOG.md
README.md
bin/cfg/Tomb1Main_gameflow.json5
bin/cfg/Tomb1Main_gameflow_ub.json5

Resolves #356.
Adds credit music.
...

gameflow: add music to credits

---

CHANGELOG.md
README.md
bin/cfg/Tomb1Main_gameflow.json5
bin/cfg/Tomb1Main_gameflow_ub.json5
src/game/gameflow.c
src/game/gameflow.h
src/game/stats.c

gameflow: add support for unobtainable pickups and kills

---

bin/cfg/Tomb1Main_gameflow_ub.json5

Adds a stat screen to the end of Unfinished Business. Should have been included in #469 so it doesn't need a separate changelog.
...

gamflow_ub: add stats screen to the end of Unfinished Business

---

src/game/option_graphics.c

option/graphics: fix broken perspective dialog

---

src/game/option_control.c
src/game/option_graphics.c
src/game/option_passport.c
src/game/option_sound.c
src/game/output.c
src/game/text.c

Resolves #480. Regression from f14ec7e0.
Resolves #480

text: fix broken 8 glyph

---

CHANGELOG.md
README.md
bin/cfg/Tomb1Main.json5
src/config.c
src/config.h
src/game/inventry.c

Resolves #309.
Added the option to pause sound in the inventory screen.
...

inventry: add the option to pause sound in the inventory

---

CHANGELOG.md
src/game/output.c

output: fix ghost margins during fades

---

CHANGELOG.md
src/game/objects/pickup.c

Resolves #500.
Fixed picking up multiple underwater pickups when walk_to_items is enabled
...

pickup: fix multiple underwater pickups with walk_to_items

---

CHANGELOG.md
src/game/objects/pickup.c

Resolves #505.
Added the ability to pick up multiple items at once with walk to items enabled.
...

pickup: add ability to pick up multiple items with walk to items

---

CHANGELOG.md
src/game/gameflow.c

Improve picture fades

---

src/game/game.c
src/game/inventry.c
src/game/objects/save_crystal.c
src/game/option_passport.c
src/global/types.h

Create enums for g_InvExtraData to improve code readability.
...

passport: create enums for g_InvExtraData

---

CHANGELOG.md
src/3dsystem/matrix.c
src/game/draw.c
src/game/draw.h

Resolves #506.
Added a matrix stack overflow error check and message if GetRoomBounds runs infinitely.
...
Let me know if this is what you had in mind. Example crash output for #227:
```
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5 …
```

matrix: add a matrix stack overflow error check and crash message
